version: '{build}'

# Build worker image (VM template)
image: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug
  - Release

before_build:
  - if not exist build mkdir build
  - cd build
  - cmake --version
  - cmake ..
  
build:
  project: build\CactusJumpTests.sln
  parallel: true
  
after_build:
  - 7z a tests.zip '.\build\$(configuration)\*.exe' '.\build\lib\$(configuration)\*.dll'
  
artifacts:
  - path: tests.zip
    name: tests
