version: '{build}'

clone_folder: c:\projects\cactusjump

# Build worker image (VM template)
image: Visual Studio 2015

configuration:
- Release
- Debug

platform:
- x64

cache:
  - build/googletest-source
  - build/googletest-download
  
environment:
  matrix:
  - arch: Win64

before_build:
- cmd: mkdir build && cd build && cmake --version && cmake ..
  
build:
  project: c:\projects\cactusjump\build\CactusJumpTests.sln
  parallel: true