version: '{build}'

# Build worker image (VM template)
image: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug
  - Release
  
install:
  - pip install -U platformio

before_build:
  - if not exist build mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - cd %APPVEYOR_BUILD_FOLDER%
  
build:
  project: build\CactusJumpTests.sln
  parallel: true
  verbosity: minimal
  
after_build:
  - copy build\lib\%CONFIGURATION%\*.dll build\%CONFIGURATION%
  - 7z a tests.zip %APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\*.exe %APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\*.dll
  - echo %cd%
  - dir

test_script:
  - build\asset.exe
  - build\collision.exe
  - build\player.exe
  - platformio run -S

artifacts:
  - path: tests.zip
