version: '{build}'

# Build worker image (VM template)
image: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug
  - Release

before_build:
  - if not exist build mkdir build
  - cd build
  - cmake --version
  - cmake ..
  
build:
  project: build\CactusJumpTests.sln
  parallel: true
  
  verbosity: minimal
  
after_build:
  - 7z a tests.zip %APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\*.exe %APPVEYOR_BUILD_FOLDER%\build\lib\%CONFIGURATION%\*.dll
  
artifacts:
  - path: %APPVEYOR_BUILD_FOLDER%\tests.zip
    name: tests
