version: '{build}'

clone_folder: c:\projects\cactusjump

# Build worker image (VM template)
image: Visual Studio 2015

configuration:
  - Debug
  - Release

cache:
  - build\googletest-source
  - build\googletest-download

before_build:
  - cmd: mkdir -p build && cd build && cmake --version && cmake ..
  
build:
  project: build\CactusJumpTests.sln
  parallel: true
  
artifacts:
  - path: 'build\*.exe'
  - name: test executables
  
  - path: 'build\lib\*.dll'
  - name: libraries
