version: '{build}'

# Build worker image (VM template)
image: Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

cache:
  - build\googletest-src
  - build\googletest-download

before_build:
  - cmd: if not exist build mkdir build && cd build && cmake --version && cmake .. && cd ..
  
build:
  project: build\CactusJumpTests.sln
  parallel: true
  
artifacts:
  - path: '**\*.exe'
    name: test executables
  
  - path: '**\lib\*.dll'
    name: libraries
