version: '{build}'

# Build worker image (VM template)
image: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug
  - Release

cache:
  - build\googletest-src
  - build\googletest-download

before_build:
  - cmd: if not exist build mkdir build && cd build && cmake --version && cmake .. && cd ..
  
build:
  project: build\CactusJumpTests.sln
  parallel: true
  
artifacts:
  - path: 'build\$(configuration)\*.exe'
    name: test executables
  
  - path: 'build\lib\$(configuration)\*.dll'
    name: libraries
